helper/urls.py
from django.urls import path

from helper.apps import HelperConfig
from helper.views import HelperListView, CategoryListView, HelperDetailView, HelperUpdateView, HelperDeleteView

app_name = HelperConfig.name

urlpatterns = [
    path('category/', HelperListView.as_view(), name='list'),
    path('', CategoryListView.as_view(), name='category_list'),
    path('<int:pk>/', HelperDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', HelperUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', HelperDeleteView.as_view(), name='delete')
]

helper_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('helper/', include('helper.urls', namespace='helper')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

helper/models.py
from django.db import models


NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):

    title = models.CharField(max_length=150, verbose_name='заголовок')

    preview = models.ImageField(upload_to='helper', verbose_name='превью', **NULLABLE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = "Категории"


class Helper(models.Model):
    STATUS_NEW = 'new'
    STATUS_DRAFT = 'draft'
    STATUS_PUBLISHED = 'published'

    STATUSES = (
        (STATUS_NEW, 'новая'),
        (STATUS_DRAFT, 'черновик'),
        (STATUS_PUBLISHED, 'опубликовано'),
    )

    title = models.CharField(max_length=150, verbose_name='заголовок')
    body = models.TextField(verbose_name='содержимое')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    status = models.CharField(choices=STATUSES, default=STATUS_NEW, max_length=10, verbose_name='статус')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Шпаргалка'
        verbose_name_plural = "Шпаргалки"

helper/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from helper.models import Helper, Category


class HelperListView(ListView):
    model = Helper

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.GET.get('cat', None):
            category = self.request.GET.get('cat')
            return queryset.filter(category__id=category).all()


class HelperDetailView(DetailView):
    model = Helper


class HelperUpdateView(UpdateView):
    model = Helper
    fields = ('title', 'body',)
    success_url = reverse_lazy('helper:category_list')


class HelperCreateView(CreateView):
    model = Helper
    fields = ('title', 'body',)
    success_url = reverse_lazy('helper:category_list')


class HelperDeleteView(DeleteView):
    model = Helper
    success_url = reverse_lazy('helper:category_list')


class CategoryListView(ListView):
    model = Category

templates/helper/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>
<body>

    {% block content %}

    {% endblock %}


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/helper/category_list.html
{% extends 'helper/base.html' %}
{% block content %}
<h1>{{ page_title }}</h1>
    <div class="container">
    <table>
        {% for object in object_list %}
            <tr>
            <td> <img class="card-img-top w-25" src="/media/{{ object.preview }}" alt="Card image cap"></td>
            <td>{{ object.title }}</td>
                <td><a href="category/?cat={{ object.pk }}">просмотр</a></td>
            </tr>
        {% endfor %}
    </table>
    </div>


{% endblock %}

templates/helper/helper_confirm_delete.html
{% extends 'helper/base.html' %}

{% block content %}
    <p>
    Уверены, что хотите удалить шпаргалку "{{ object.title }}"?
    </p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">подтвердить</button>
    </form>
    <a href="{% url 'helper:category_list' %}">передумал</a>
{% endblock %}

templates/helper/helper_detail.html
{% extends 'helper/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    {{ object.title }}
                    <hr>
                    {{ object.body }}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/helper/helper_form.html
{% extends 'helper/base.html' %}
{% block content %}
    <form method="post">
    {% csrf_token %}
        {{ form.as_p }}
    <button type="submit">Создать</button>
    <a href="{% url 'helper:category_list' %}">Отмена</a>
    </form>
{% endblock %}

templates/helper/helper_list.html
{% extends 'helper/base.html' %}

{% block content %}

    <div class="row mt-5">
        {% for item in object_list %}
            <div class="col-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ item.title }}</h5>
                        <p class="card-text">{{ item.body|slice:10 }}...</p>
                        <a href="{% url 'helper:detail' item.pk %}" class="btn btn-primary">Читать далее</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <table>
        {% for object in object_list %}
            <tr>
                <td><a href="{% url 'helper:update' object.pk %}">изменить</a></td>
                <td><a href="{% url 'helper:delete' object.pk %}">удалить</a></td>
            </tr>
        {% endfor %}
    </table>
    <hr>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link"
                                         href="{% url 'helper:list' %}?page={{ page_obj.previous_page_number }}">Назад</a>
                </li>
            {% endif %}
            <li class="page-item"><a class="page-link">{{ page_obj.number }} / {{ page_obj.paginator.count }}</a></li>
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="{% url 'helper:list' %}?page={{ page_obj.next_page_number }}">Вперед</a></li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}